### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by ProProfessor** [aminography/PrimeDatePicker#5]
java.lang.NullPointerException
        at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
        at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:89)
        at android.graphics.Typeface.createFromAsset(Typeface.java:225)
        at com.aminography.primedatepicker.fragment.PrimeDatePickerBottomSheet.onInitViews(PrimeDatePickerBottomSheet.kt:66)
        at com.aminography.primedatepicker.fragment.BaseBottomSheetDialogFragment.setupDialog(BaseBottomSheetDialogFragment.kt:27)
        at com.aminography.primedatepicker.fragment.PrimeDatePickerBottomSheet.setupDialog(PrimeDatePickerBottomSheet.kt:28)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:383)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1403)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1821)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by jonspiro** [comment]
make sure you have added the PrimeCalendar library https://github.com/aminography/PrimeCalendar

1. let your activity activity implement PrimeDatePickerBottomSheet.OnDayPickedListener

2.  in your activity's onCreate method,  

CalendarType calendarType = CalendarType.CIVIL;  //use type that suits your use case
 PrimeCalendar today = CalendarFactory.newInstance(calendarType);
        
datePicker = PrimeDatePickerBottomSheet.newInstance (today, null , null , PickType.RANGE_START, null, new CivilCalendar(), new CivilCalendar(), "fonts/sf_ui_regular.ttf");

// edit parameters to suit ur use case

3. set onDatesetListener to your picker finally display your date picker bottom sheet by calling 
     datePicker.show(getSupportFragmentManager());

**Comment by ProProfessor** [comment]
It still happens, but it says that cannot found the fonts resource

**Comment by aminography** [comment]
Do you pass the font path correctly to the `PrimeDatePickerBottomSheet.newInstance()`?

**Comment by dovahkrid** [comment]
so the font is must-have, not "can be null" ?

**Comment by jonspiro** [comment]
> Do you correctly pass the font path to the `PrimeDatePickerBottomSheet.newInstance()`?

yes pass the font directly or through a variable any of them will work..i passed the font directly though

**Comment by jonspiro** [comment]
> so the font is must-have, not "can be null" ?

yes looks like it, passing null produces a null pointer exception

**Comment by jonspiro** [comment]
> It still happens, but it says that cannot found the fonts resource

double check your fonts directory

**Comment by aminography** [comment]
I have fixed it. Try to use `1.0.7` version. Sorry for late response.
